name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch tags
      run: git fetch --prune --tags
    - name: Cake
      run: ./build.ps1
      env:
        NuGetApiKey: ${{ secrets.NuGetApiKey }}
        FeedzApiKey: ${{ secrets.FeedzApiKey }}
